// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// shake_internal
Rcpp::List shake_internal(Rcpp::List& graph);
RcppExport SEXP _shaker_shake_internal(SEXP graphSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type graph(graphSEXP);
    rcpp_result_gen = Rcpp::wrap(shake_internal(graph));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_shaker_shake_internal", (DL_FUNC) &_shaker_shake_internal, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_shaker(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
